# Docker Compose Keycloak Postgres ( Docker compose for Keycloak with Postgres Database).

version: '3.1'


volumes:
  postgres_data:
      driver: local


services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: jboss/keycloak:10.0.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        KEYCLOAK_HOSTNAME: hostname_here
        VIRTUAL_PORT: "8080"
        KEYCLOAK_FRONTEND_URL: https://<hostname_here>/auth
        PROXY_ADDRESS_FORWARDING: "true" # <==== very important if you use reverse proxy

      ports:
        - 8080:8080
      depends_on:
        - postgres
